spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
com:
  skyraining:
    title: 了解一下
    description: 问题不大
server:
  port: 8089