spring:
# mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dataName
    username: root
    password:
# redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
# mongo
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/mongodbName
      option:
        server-selection-timeout: 120000
        connect-timeout: 120000
        max-wait-time: 120000
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000


