spring:
  profiles:
    active: dev
# jpa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
# thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    check-template: true
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5

com:
  skyraining:
    title: 了解一下
    description: 问题不大
server:
  port: 8089